### ISSUE TITLE
pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require

### ISSUE THREAD

**Issue by marcbuchser** [sothawo/kovasbak#1]
> cd 
> docker build -t kovasbak-kafkabase .
Sending build context to Docker daemon  45.51MB
Step 1/6 : FROM frolvlad/alpine-oraclejdk8:8.131.11-slim
pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by marcbuchser** [comment]
get a dockerhub account and login 

> docker login
(username and password)

**Comment by marcbuchser** [comment]
actually....same error appears after logging in.

**Comment by sothawo** [comment]
that image does not exist anymore in docker hub. Seems I need to update this project to a different jdk  image

**Comment by sothawo** [comment]
I updated the demo with working docker base images
